services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'desafio-meal'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3309:3306"
    expose:
      - '3309'
    volumes:
      - E:\Projetos-Codes\FlaskFoguete\DESAFIO_DIET\mysql:\var\lib\mysql