"""Modificando Tabela

Revision ID: 68bf6663073d
Revises: dc639342cfaf
Create Date: 2025-08-11 17:25:29.487451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bf6663073d'
down_revision = 'dc639342cfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloria', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('caloria')

    # ### end Alembic commands ###
